### ISSUE TITLE
Show current song instead previous song?

### ISSUE THREAD

**Issue by pibo5** [drumsoft/Traktor-SongNameServer#4]
Hi,

First of all, congratulations for your work. 

I´ve been running the Traktor-SongNameServer in Mac OS X 10.10.4 and Perl 5.16.0, but for some reason the "Artist and Title" info of the current track is shown several seconds after you´ve played the next song. I don´t know if it´s just in my case, but this way it doesn´t make sense as the info showed is not in real time so the "Artist - Song" never match in time with the played track. I´ve tested the output within Terminal [son changed: XX - XX] and Quartz Composer via Traktor Song.qtz.

Is there any way to make the "Artist - Song Title"shows i.e. about 10 secs after you play the song, instead some seconds after you´ve play the next one? Maybe for Twitter it´s not important, but I think if want to use it for showing that info during a performance in a club (wihtin a display, projector, etc.) in real time, it should match the info with the current song in time. 

Thank you in advance.

**Comment by drumsoft** [comment]
Thank you for trying my project.
If you are launching server from songnameserver.pl, some configurations are in this file. Change option->cue->bysong to 0 (default is 1) and option->cue->bytime to 10 (secs. default is 0).

**Comment by pibo5** [comment]
Hi @drumsoft,

It works like a charm, thank you for your help.

PS. One last thing, the output seems to be in xml format, where is (if exists) the .xml file saved?

Regards.

**Comment by drumsoft** [comment]
the output xml is not saved. It comes from template written in Traktor/SongNameServer.pm (It's not good design :) )
